### ISSUE TITLE
Problems using this Shortcut

### ISSUE THREAD

**Issue by ChefrenToo** [FuturraGroup/ChatGPT-Shortcut#1]
When reting to run this shortcut and entering or speaking the question, I get the following error message:

‘Sorry, something went wrong. Shortcuts says, "In", no value was found for dictionary key 'choices!!”

What goes wrong, and what can be done about this error message.

I am running Ios 16.5 beta 2

Any help would be greatly appreciated

**Comment by sergey-zhuravel** [comment]
hi, check your balance in your OpenAI account. Perhaps you didn't add the payment method.
