### ISSUE TITLE
"The file doesn't exist"

### ISSUE THREAD

**Issue by miltonTouchdown** [FuturraGroup/ChatGPT-Shortcut#2]
After the request, the shortcut show an error: "The file doesn't exist"
I attach an image with the error.

Regards!
![errorr](https://user-images.githubusercontent.com/11322253/232247291-f960562b-1927-4d6b-9f46-96accef61d77.jpg)

**Comment by sergey-zhuravel** [comment]
check this item in your settings:
> For correct work continuous conversations, you need to turn on the “Settings” -> Apple ID -> iCloud -> iCloud Drive function to use the save to TXT file function.
