### ISSUE TITLE
Bug when installing shortcut 

### ISSUE THREAD

**Issue by imagineapps1** [FuturraGroup/ChatGPT-Shortcut#5]
![IMG_2819](https://github.com/FuturraGroup/ChatGPT-Shortcut/assets/89914463/24f206db-408c-474b-87d5-2543dedd94eb)
![IMG_2818](https://github.com/FuturraGroup/ChatGPT-Shortcut/assets/89914463/f274bfdf-aa73-4064-ad35-7221b2b40227)

After following all steps, it appears this bug. 
I’m on iOS17

**Comment by imagineapps1** [comment]
> hi, check your balance in your OpenAI account. Perhaps you didn't add the payment method.

I’m a  Subscriber and I have a payment method. Any other Recommendations?

**Comment by sergey-zhuravel** [comment]
This error is only due to account payment. You may have reached your limit, check the 'Usage limits' section. There are limits even on a paid account.
