### ISSUE TITLE
ChatGPT3.5 often not working using Siri but using as Shortcut

### ISSUE THREAD

**Issue by Shariner** [FuturraGroup/ChatGPT-Shortcut#6]
Hi,

I tested the shortcut a little bit since yesterday. If I choose ChatGPT 4 as model the shortcut is working with the Hey Siri Command and on manual execution.

But if I choose ChatGPT3.5 as model the manual execution is working everytime but using chatGPT 3.5 with Hey Siri leads often to an error. The error: An error occurred, please try again later. 
Sometime it’s working fine even with Siri.

It looks like to me it is timing out as the answer takes much longer than on ChatGPT 4. Is this possible and can be increased in any way?

**Comment by sergey-zhuravel** [comment]
Most likely the problem is with your Internet, try using another Internet. Others don't have this problem.
