### ISSUE TITLE
Steps in shortcut configuration.

### ISSUE THREAD

**Issue by abadger13** [FuturraGroup/ChatGPT-Shortcut#7]
Two issues: 

First, I view api.openai.com and I see only error script:

{
  "error": {
    "message": "Invalid URL (GET /)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

Second (caused by the error?)
I get to the privacy pop up and I am only invited to allow Chrome. No allow for the api. 

Not sure how to proceed?

**Comment by sergey-zhuravel** [comment]
You need to give permission to use the API, I don’t know why this permission doesn’t appear for you. Try rebooting your phone or reinstalling the shortcut.
